LibraryProject/Components/CartSummaryViewComponent.cs
using LibraryProject.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryProject.Components
{   //inherits from View component class
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }

}

LibraryProject/Components/NavigationMenuViewComponent.cs
using LibraryProject.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace LibraryProject.Components
{
    public class NavigationMenuViewComponent : ViewComponent
    {

        // declared Iquerable list of books IBookRepository.cs
        private IBookRepository repository;

        public NavigationMenuViewComponent (IBookRepository b)
        {
            //set repository made ^ and set it equal to b
            repository = b;
        }

        //automatically called when ViewComponent is added to screen
        public IViewComponentResult Invoke() 
            
        {
            //pulls data called "category" from url and puts it into the viewbag
            ViewBag.SelectedCategory = RouteData?.Values["category"];

            //queries and gets data from the repository, selects certain ones, makes sure they are unique, then orders by them sends to "default page"
            return View(repository.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x));
        }
    }
}

LibraryProject/Views/Shared/BookSummary.cshtml
@model Book

<div>
    <h1 class="container">Title: @Model.Title</h1>
    <h5 class="container">Author: @Model.Author</h5>
    <h5 class="container">Publisher: @Model.Publisher</h5>
    <h5 class="container">ISBN: @Model.ISBN</h5>
    <h5 class="container">Category: @Model.Category</h5>
    <h5 class="container">Class: @Model.Class</h5>
    <h5 class="container"><mark>$@Model.Price</mark></h5>
    <h5 class="container">@Model.NumPages Pages</h5>

</div>
<div> <!--type="hidden" is just to get info from one place to another-->
    <form id="@Model.BookId" asp-page="/Shop" method="post">
        <input type="hidden" asp-for="BookId"/>
        <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
        <span class="card-text p-1">
           
            <button type="submit" class="btn-success btn-sm pull-right" style="float:right">
                Add to Cart
            </button>
        </span>
    </form>
</div>

LibraryProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LibraryProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">Library</div>
                <div class="col-6 text-right">
                    <!--adds cart summary componet-->
                    <vc:cart-summary />
                </div>
            </div>
        </div>
    </div>
    <div class="bg-dark text-white p-2">
        <span class="navbar-brand ml-2">Glorious Knowledges</span>
    </div>
    <!--puts in the Navigation View Component-->
    <vc:navigation-menu />

    @RenderBody()

</body>
</html>